from __future__ import annotations

from unittest.mock import patch

import yaml

from folio.core.init import (
    AVAILABLE_PROFILES,
    _abbreviate,
    _minimal_config,
    _write_env_key,
    _write_yaml,
    init_project,
)

# ── Unit: _abbreviate ────────────────────────────────────────────────────────

class TestAbbreviate:
    def test_single_word(self):
        assert _abbreviate("Toronto") == "TOR"

    def test_multi_word(self):
        assert _abbreviate("Ontario Arts Council") == "OAC"

    def test_two_words(self):
        assert _abbreviate("Canada Council") == "CC"

    def test_skips_non_alpha_starting_words(self):
        assert _abbreviate("123 Test") == "T"

    def test_short_single_word(self):
        assert _abbreviate("AB") == "AB"


# ── Unit: _minimal_config ────────────────────────────────────────────────────

class TestMinimalConfig:
    def test_defaults_with_no_args(self):
        cfg = _minimal_config()
        assert cfg["org"]["name"] == "My Organization"
        assert cfg["org"]["abbreviation"] == "MO"
        assert cfg["funders"] == {}
        assert cfg["doc_types"] == []
        assert cfg["paths"]["raw_archive"] == "./_raw_archive/"
        assert "My Organization Grant Archive" in cfg["project"]["name"]

    def test_custom_org_name(self):
        cfg = _minimal_config(org_name="Test Gallery")
        assert cfg["org"]["name"] == "Test Gallery"
        assert "Test Gallery Grant Archive" in cfg["project"]["name"]

    def test_custom_funders(self):
        cfg = _minimal_config(funders={"CAC": "Canada Council", "OAC": "Ontario Arts Council"})
        assert cfg["funders"] == {"CAC": "Canada Council", "OAC": "Ontario Arts Council"}

    def test_custom_doc_types(self):
        cfg = _minimal_config(doc_types=["application", "report", "budget"])
        assert cfg["doc_types"] == ["application", "report", "budget"]

    def test_custom_raw_archive(self):
        cfg = _minimal_config(raw_archive="/data/archive/")
        assert cfg["paths"]["raw_archive"] == "/data/archive/"

    def test_all_custom(self):
        cfg = _minimal_config(
            org_name="Custom Org",
            funders={"F1": "Funder One"},
            doc_types=["type1", "type2"],
            raw_archive="/custom/path/",
        )
        assert cfg["org"]["name"] == "Custom Org"
        assert cfg["funders"] == {"F1": "Funder One"}
        assert cfg["doc_types"] == ["type1", "type2"]
        assert cfg["paths"]["raw_archive"] == "/custom/path/"


# ── Unit: _write_yaml ────────────────────────────────────────────────────────

class TestWriteYaml:
    def test_writes_valid_yaml(self, tmp_path):
        output = tmp_path / "folio.yaml"
        config = {
            "project": {"name": "Test"},
            "org": {"name": "Test Org"},
            "funders": {"CAC": "Canada Council"},
        }
        _write_yaml(output, config)

        assert output.exists()
        content = output.read_text()
        assert "# folio project configuration" in content
        assert "Generated by `folio init`" in content

        # Verify it's valid YAML
        parsed = yaml.safe_load(content)
        assert parsed["project"]["name"] == "Test"
        assert parsed["org"]["name"] == "Test Org"

    def test_writes_complex_config(self, tmp_path):
        output = tmp_path / "folio.yaml"
        config = {
            "project": {"name": "Complex"},
            "org": {
                "name": "Complex Org",
                "abbreviation": "CO",
                "description": "A complex org.",
            },
            "funders": {"A": "AAA", "B": "BBB"},
            "doc_types": ["app", "rep"],
            "paths": {"raw_archive": "./archive/"},
        }
        _write_yaml(output, config)

        parsed = yaml.safe_load(output.read_text())
        assert parsed["funders"]["A"] == "AAA"
        assert parsed["funders"]["B"] == "BBB"
        assert parsed["org"]["abbreviation"] == "CO"


# ── Unit: _write_env_key ─────────────────────────────────────────────────────

class TestWriteEnvKey:
    def test_writes_new_env_file(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        _write_env_key("test-api-key-12345")
        env_path = tmp_path / ".env"
        assert env_path.exists()
        content = env_path.read_text()
        assert "DEEPSEEK_API_KEY=test-api-key-12345" in content

    def test_appends_to_existing_env_file(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        env_path = tmp_path / ".env"
        env_path.write_text("EXISTING_KEY=value\n")

        _write_env_key("new-api-key")
        content = env_path.read_text()
        assert "EXISTING_KEY=value" in content
        assert "DEEPSEEK_API_KEY=new-api-key" in content

    def test_skips_if_ds_key_exists(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        env_path = tmp_path / ".env"
        env_path.write_text("DEEPSEEK_API_KEY=existing-key\nOTHER=val\n")

        _write_env_key("should-not-write")
        content = env_path.read_text()
        assert "should-not-write" not in content
        assert "DEEPSEEK_API_KEY=existing-key" in content

    def test_adds_newline_before_appending(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        env_path = tmp_path / ".env"
        env_path.write_text("NO_NEWLINE_AT_END=value")

        _write_env_key("key1")
        content = env_path.read_text()
        assert "NO_NEWLINE_AT_END=value\nDEEPSEEK_API_KEY=key1" in content


# ── Integration: init_project ────────────────────────────────────────────────

class TestInitProject:
    @patch("folio.core.init._BUILTIN_DEFAULTS")
    def test_init_with_profile(self, mock_defaults, tmp_path):
        mock_defaults.read_text.return_value = yaml.dump({
            "project": {"name": "folio"},
            "org": {"name": "Default Org", "abbreviation": "DO"},
            "paths": {"raw_archive": "./archive/"},
            "converter": {"type": "liteparse"},
            "llm": {
                "provider": "deepseek",
                "models": {"fast": "test-fast", "quality": "test-pro"},
            },
        })

        output = tmp_path / "folio.yaml"
        # Patch the profiles_base
        with patch("folio.core.init._PROFILES_BASE") as mock_profiles_base:
            mock_profiles_base.__truediv__.return_value.read_text.return_value = yaml.dump({
                "org": {"name": "Canadian Gallery"},
                "funders": {"CAC": "Canada Council for the Arts"},
                "doc_types": ["application", "report"],
            })

            result = init_project(
                output_path=output,
                profile="canadian-gallery",
                org_name="My Gallery",
                funders={"OAC": "Ontario Arts Council"},
                raw_archive="/my/archive/",
            )

        assert output.exists()
        assert result["config_path"] == str(output.resolve())
        assert result["profile"] == "canadian-gallery"

        parsed = yaml.safe_load(output.read_text())
        assert parsed["org"]["name"] == "My Gallery"
        assert parsed["funders"]["OAC"] == "Ontario Arts Council"
        assert parsed["paths"]["raw_archive"] == "/my/archive/"

    @patch("folio.core.init._BUILTIN_DEFAULTS")
    def test_init_minimal_no_profile(self, mock_defaults, tmp_path):
        mock_defaults.read_text.return_value = yaml.dump({
            "project": {"name": "folio"},
            "org": {"name": "Default Org", "abbreviation": "DO"},
            "paths": {"raw_archive": "./archive/"},
            "converter": {"type": "liteparse"},
            "llm": {
                "provider": "deepseek",
                "models": {"fast": "test-fast", "quality": "test-pro"},
            },
        })

        output = tmp_path / "folio.yaml"
        result = init_project(
            output_path=output,
            org_name="Test Org",
            funders={"TAC": "Toronto Arts Council"},
            doc_types=["application"],
            raw_archive="./my_docs/",
        )

        assert output.exists()
        parsed = yaml.safe_load(output.read_text())
        assert parsed["org"]["name"] == "Test Org"

    @patch("folio.core.init._BUILTIN_DEFAULTS")
    def test_init_with_scan_file(self, mock_defaults, tmp_path):
        mock_defaults.read_text.return_value = yaml.dump({
            "project": {"name": "folio"},
            "org": {"name": "Default Org", "abbreviation": "DO"},
            "paths": {"raw_archive": "./archive/"},
            "converter": {"type": "liteparse"},
            "llm": {
                "provider": "deepseek",
                "models": {"fast": "test-fast", "quality": "test-pro"},
            },
        })

        scan_path = tmp_path / "scan_report.yaml"
        scan_path.write_text(yaml.dump({
            "source_path": "/scanned/archive/",
            "total_files": 42,
            "by_funder": {
                "CAC": {"count": 5, "full_name": "Canada Council for the Arts"},
                "OAC": {"count": 3, "full_name": "Ontario Arts Council"},
            },
            "by_type": {
                "application": 4,
                "report": 3,
                "budget": 1,
            },
        }))

        output = tmp_path / "folio.yaml"
        result = init_project(
            output_path=output,
            from_scan=scan_path,
            org_name="Scanned Org",
        )

        assert output.exists()
        parsed = yaml.safe_load(output.read_text())
        assert parsed["funders"]["CAC"] == "Canada Council for the Arts"
        assert parsed["funders"]["OAC"] == "Ontario Arts Council"
        assert "application" in parsed["doc_types"]
        assert "report" in parsed["doc_types"]
        assert "budget" in parsed["doc_types"]

    def test_init_guided_dry_run(self, tmp_path):
        output = tmp_path / "folio.yaml"
        result = init_project(
            output_path=output,
            guided=True,
            dry_run=True,
        )
        assert "Cannot preview guided setup" in result["warnings"][0]
        assert not output.exists()

    @patch("folio.core.init._BUILTIN_DEFAULTS")
    def test_no_funders_warning(self, mock_defaults, tmp_path):
        mock_defaults.read_text.return_value = yaml.dump({
            "project": {"name": "folio"},
            "org": {"name": "Default Org", "abbreviation": "DO"},
            "paths": {"raw_archive": "./archive/"},
            "converter": {"type": "liteparse"},
            "llm": {
                "provider": "deepseek",
                "models": {"fast": "test-fast", "quality": "test-pro"},
            },
        })

        output = tmp_path / "folio.yaml"
        result = init_project(
            output_path=output,
            org_name="Orphan Org",
        )

        assert len(result["warnings"]) > 0
        assert any("No funders configured" in w for w in result["warnings"])

    @patch("folio.core.init._BUILTIN_DEFAULTS")
    def test_dry_run_does_not_write_file(self, mock_defaults, tmp_path):
        mock_defaults.read_text.return_value = yaml.dump({
            "project": {"name": "folio"},
            "org": {"name": "Default Org", "abbreviation": "DO"},
            "paths": {"raw_archive": "./archive/"},
            "converter": {"type": "liteparse"},
            "llm": {
                "provider": "deepseek",
                "models": {"fast": "test-fast", "quality": "test-pro"},
            },
        })

        output = tmp_path / "folio.yaml"
        result = init_project(
            output_path=output,
            org_name="Dry Run Org",
            dry_run=True,
        )

        assert not output.exists()
        assert result["merged_config"] is not None
        assert result["config_path"] == str(output.resolve())

    @patch("folio.core.init._BUILTIN_DEFAULTS")
    def test_merged_config_contains_defaults(self, mock_defaults, tmp_path):
        mock_defaults.read_text.return_value = yaml.dump({
            "project": {"name": "folio"},
            "org": {"name": "Default Org", "abbreviation": "DO"},
            "converter": {"type": "liteparse"},
            "llm": {
                "provider": "deepseek",
                "models": {"fast": "fast-model", "quality": "pro-model"},
                "base_url": "https://api.deepseek.com",
            },
        })

        output = tmp_path / "folio.yaml"
        result = init_project(
            output_path=output,
            org_name="Merged Org",
        )

        merged = result["merged_config"]
        assert "converter" in merged
        assert "llm" in merged
        assert merged["org"]["name"] == "Merged Org"

    @patch("folio.core.init._BUILTIN_DEFAULTS")
    @patch("folio.core.init._PROFILES_BASE")
    def test_available_profiles_list(self, mock_profiles_base, mock_defaults, tmp_path):
        mock_defaults.read_text.return_value = yaml.dump({
            "project": {"name": "folio"},
            "org": {"name": "Default Org", "abbreviation": "DO"},
            "paths": {"raw_archive": "./archive/"},
            "converter": {"type": "liteparse"},
            "llm": {
                "provider": "deepseek",
                "models": {"fast": "test-fast", "quality": "test-pro"},
            },
        })
        mock_profiles_base.__truediv__.return_value.read_text.return_value = yaml.dump({
            "org": {"name": "Test Profile"},
        })

        output = tmp_path / "folio.yaml"
        result = init_project(
            output_path=output,
            profile="canadian-festival",
        )
        assert result["profile"] == "canadian-festival"

    def test_available_profiles_constant(self):
        assert "canadian-artist-run-centre" in AVAILABLE_PROFILES
        assert "canadian-gallery" in AVAILABLE_PROFILES
        assert "canadian-festival" in AVAILABLE_PROFILES
        assert "generic" in AVAILABLE_PROFILES
        assert len(AVAILABLE_PROFILES) > 0


# ── Edge Cases ───────────────────────────────────────────────────────────────

class TestEdgeCases:
    @patch("folio.core.init._BUILTIN_DEFAULTS")
    def test_overwrite_existing_config(self, mock_defaults, tmp_path):
        mock_defaults.read_text.return_value = yaml.dump({
            "project": {"name": "folio"},
            "org": {"name": "Default Org", "abbreviation": "DO"},
            "paths": {"raw_archive": "./archive/"},
            "converter": {"type": "liteparse"},
            "llm": {
                "provider": "deepseek",
                "models": {"fast": "test-fast", "quality": "test-pro"},
            },
        })

        output = tmp_path / "folio.yaml"
        output.write_text("old content")

        result = init_project(
            output_path=output,
            org_name="New Org",
        )

        parsed = yaml.safe_load(output.read_text())
        assert parsed["org"]["name"] == "New Org"

    @patch("folio.core.init._BUILTIN_DEFAULTS")
    def test_profile_without_funders(self, mock_defaults, tmp_path):
        mock_defaults.read_text.return_value = yaml.dump({
            "project": {"name": "folio"},
            "org": {"name": "Default Org", "abbreviation": "DO"},
            "paths": {"raw_archive": "./archive/"},
            "converter": {"type": "liteparse"},
            "llm": {
                "provider": "deepseek",
                "models": {"fast": "test-fast", "quality": "test-pro"},
            },
        })

        with patch("folio.core.init._PROFILES_BASE") as mock_profiles_base:
            mock_profiles_base.__truediv__.return_value.read_text.return_value = yaml.dump({
                "org": {"name": "No Funder Profile"},
                "doc_types": ["application"],
            })

            output = tmp_path / "folio.yaml"
            result = init_project(
                output_path=output,
                profile="canadian-gallery",
            )
            assert "No funders configured" in result["warnings"][0]

    @patch("folio.core.init._BUILTIN_DEFAULTS")
    def test_guards_against_no_llm_in_defaults(self, mock_defaults, tmp_path):
        mock_defaults.read_text.return_value = yaml.dump({
            "project": {"name": "folio"},
            "org": {"name": "Default Org", "abbreviation": "DO"},
            "paths": {"raw_archive": "./archive/"},
        })

        output = tmp_path / "folio.yaml"
        result = init_project(
            output_path=output,
            org_name="Minimal Org",
        )
        merged = result["merged_config"]
        assert "project" in merged
        assert "org" in merged

    @patch("folio.core.init._BUILTIN_DEFAULTS")
    def test_scan_without_funders(self, mock_defaults, tmp_path):
        mock_defaults.read_text.return_value = yaml.dump({
            "project": {"name": "folio"},
            "org": {"name": "Default Org", "abbreviation": "DO"},
            "paths": {"raw_archive": "./archive/"},
            "converter": {"type": "liteparse"},
            "llm": {
                "provider": "deepseek",
                "models": {"fast": "test-fast", "quality": "test-pro"},
            },
        })

        scan_path = tmp_path / "scan_empty.yaml"
        scan_path.write_text(yaml.dump({
            "source_path": "/archive/",
            "total_files": 0,
            "by_funder": {},
            "by_type": {},
        }))

        output = tmp_path / "folio.yaml"
        result = init_project(
            output_path=output,
            from_scan=scan_path,
        )

        parsed = yaml.safe_load(output.read_text())
        assert "funders" not in parsed or parsed.get("funders") == {}

    @patch("folio.core.init._BUILTIN_DEFAULTS")
    def test_multiple_profiles_available(self, mock_defaults, tmp_path):
        mock_defaults.read_text.return_value = yaml.dump({
            "project": {"name": "folio"},
            "org": {"name": "Default Org", "abbreviation": "DO"},
            "paths": {"raw_archive": "./archive/"},
            "converter": {"type": "liteparse"},
            "llm": {
                "provider": "deepseek",
                "models": {"fast": "test-fast", "quality": "test-pro"},
            },
        })

        with patch("folio.core.init._PROFILES_BASE") as mock_profiles_base:
            mock_profiles_base.__truediv__.return_value.read_text.return_value = yaml.dump({
                "org": {"name": "Canadian Arts"},
                "funders": {"CAC": "Canada Council for the Arts"},
            })

            output = tmp_path / "folio.yaml"
            result = init_project(
                output_path=output,
                profile="generic-canadian-arts",
            )
            assert result["profile"] == "generic-canadian-arts"
            assert output.exists()

    @patch("folio.core.init._BUILTIN_DEFAULTS")
    def test_returns_warnings_list(self, mock_defaults, tmp_path):
        mock_defaults.read_text.return_value = yaml.dump({
            "project": {"name": "folio"},
            "org": {"name": "Default Org", "abbreviation": "DO"},
            "paths": {"raw_archive": "./archive/"},
            "converter": {"type": "liteparse"},
            "llm": {
                "provider": "deepseek",
                "models": {"fast": "test-fast", "quality": "test-pro"},
            },
        })

        output = tmp_path / "folio.yaml"
        result = init_project(
            output_path=output,
            org_name="Test",
        )
        assert isinstance(result["warnings"], list)

    @patch("folio.core.init._BUILTIN_DEFAULTS")
    def test_write_yaml_sorts_keys_as_configured(self, mock_defaults, tmp_path):
        mock_defaults.read_text.return_value = yaml.dump({
            "project": {"name": "folio"},
            "org": {"name": "Default Org", "abbreviation": "DO"},
            "paths": {"raw_archive": "./archive/"},
            "converter": {"type": "liteparse"},
            "llm": {
                "provider": "deepseek",
                "models": {"fast": "test-fast", "quality": "test-pro"},
            },
        })

        output = tmp_path / "folio.yaml"
        result = init_project(
            output_path=output,
            org_name="Sorted Org",
            funders={"Z": "Last", "A": "First"},
        )
        content = output.read_text()
        # Z should appear before A (sort_keys=False, preserves insertion order)
        z_pos = content.index("Z:")
        a_pos = content.index("A:")
        assert z_pos < a_pos
